<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adress' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Automatic Route' => '',
    'Blocked At' => '',
    'Cat ID' => '',
    'Category' => '',
    'Charts' => '',
    'Client' => '',
    'Client Address' => '',
    'Client ID' => '',
    'Client Name' => '',
    'Clients' => '',
    'Confirmed At' => '',
    'Create' => '',
    'Create Category' => '',
    'Create Client' => '',
    'Create Product' => '',
    'Create Product Category' => '',
    'Create Relevador' => '',
    'Create Route' => '',
    'Create Routeclient' => '',
    'Create Survey' => '',
    'Created At' => '',
    'Day of the week' => '',
    'Delete' => '',
    'Email' => '',
    'Flags' => '',
    'ID' => '',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'Latitud' => '',
    'Longitud' => '',
    'Map' => '',
    'Order' => '',
    'Password Hash' => '',
    'Picture' => '',
    'Prioridad' => '',
    'Priority' => '',
    'Prod ID' => '',
    'Product' => '',
    'Product Categories' => '',
    'Product Cats' => '',
    'Product ID' => '',
    'Products' => '',
    'Registration Ip' => '',
    'Relevadors' => '',
    'Relevator' => '',
    'Reset' => '',
    'Route Date' => '',
    'Route ID' => '',
    'Routeclients' => '',
    'Routes' => '',
    'Search' => '',
    'Stock' => '',
    'Survey Date' => '',
    'Surveys' => '',
    'Unconfirmed Email' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User ID' => '',
    'User Lat' => '',
    'User Lng' => '',
    'User Radius' => '',
    'Username' => '',
];
